from fpdf import FPDF
from datetime import datetime
import matplotlib.pyplot as plt
import pandas as pd
import os
import re

# -----------------------------------------------------------
# Helpers: clean markdown and sanitize text
# -----------------------------------------------------------

def clean_markdown(md: str) -> str:
    """Convert markdown syntax to readable plain text for PDFs."""
    if not md:
        return ""
    md = re.sub(r"#{1,6}\s*", "", md)                 # remove headings
    md = re.sub(r"\*\*(.*?)\*\*", r"\1", md)          # bold
    md = re.sub(r"\*(.*?)\*", r"\1", md)              # italics
    md = re.sub(r"^- ", "• ", md, flags=re.MULTILINE) # bullets
    md = re.sub(r"\n{3,}", "\n\n", md)                # collapse spacing
    return md.strip()


def sanitize_text(text: str) -> str:
    """Replace unsupported symbols and markdown."""
    text = clean_markdown(text or "")
    replacements = {
        "≥": ">=", "≤": "<=", "–": "-", "—": "-", "•": "•",
        "“": '"', "”": '"', "’": "'", "‘": "'", "→": "->", "←": "<-",
        "°": " degrees", "₹": "Rs.", "€": "EUR", "£": "GBP", "Δ": "Δ"
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)
    text = re.sub(r"[^\x00-\x7FΔ]+", " ", text)
    return text.strip()

# -----------------------------------------------------------
# Visualization
# -----------------------------------------------------------

def create_kpi_charts(df: pd.DataFrame, output_dir="outputs/charts"):
    os.makedirs(output_dir, exist_ok=True)
    charts = []
    plt.style.use("seaborn-v0_8-colorblind")

    metrics = [
        ("Revenue", "Revenue (₹)"),
        ("Gross_Profit", "Gross Profit (₹)"),
        ("Gross_Margin_%", "Gross Margin (%)"),
        ("CAC_approx", "Customer Acquisition Cost (₹)"),
        ("Net_Contribution", "Net Contribution (₹)"),
    ]

    for col, label in metrics:
        if col not in df.columns:
            continue
        fig, ax = plt.subplots(figsize=(5.5, 3))
        ax.plot(df["Quarter"], df[col], marker="o", linewidth=2, color="#003366")
        ax.set_facecolor("#F8F9FB")
        ax.set_title(label, fontsize=10, fontweight="bold", color="#003366")
        ax.grid(True, alpha=0.3)
        plt.xticks(rotation=45)
        fname = os.path.join(output_dir, f"{col}.png")
        fig.tight_layout()
        plt.savefig(fname, dpi=160)
        plt.close(fig)
        charts.append(fname)
    return charts

# -----------------------------------------------------------
# Professional PDF Layout (Unicode-capable)
# -----------------------------------------------------------

class ReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.logo_path = "assets/logo.png"

        # ✅ Load Unicode fonts (Regular + Bold + Italic)
        import matplotlib
        font_dir = os.path.join(os.path.dirname(matplotlib.__file__), "mpl-data", "fonts", "ttf")
        reg_font = os.path.join(font_dir, "DejaVuSans.ttf")
        bold_font = os.path.join(font_dir, "DejaVuSans-Bold.ttf")
        italic_font = os.path.join(font_dir, "DejaVuSans-Oblique.ttf")

        self.add_font("DejaVu", "", reg_font, uni=True)
        self.add_font("DejaVu", "B", bold_font, uni=True)
        self.add_font("DejaVu", "I", italic_font, uni=True)
        self.set_font("DejaVu", "", 12)

    def header(self):
        if os.path.exists(self.logo_path):
            self.image(self.logo_path, 10, 8, 20)
        self.set_font("DejaVu", "B", 14)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, "Business Performance Review", ln=True, align="C")
        self.set_font("DejaVu", "", 9)
        self.set_text_color(60, 60, 60)
        self.cell(0, 6, datetime.now().strftime("%B %d, %Y"), ln=True, align="C")
        self.ln(5)
        self.set_text_color(0)

    def footer(self):
        self.set_y(-15)
        self.set_font("DejaVu", "I", 8)
        self.set_text_color(100)
        self.cell(0, 10, f"Page {self.page_no()}  |  Generated by Autonomous Business Consultant", 0, 0, "C")

    def section_title(self, title):
        self.set_font("DejaVu", "B", 12)
        self.set_fill_color(0, 51, 102)
        self.set_text_color(255)
        self.cell(0, 8, f"  {title}", ln=True, fill=True)
        self.set_text_color(0)
        self.ln(2)

# -----------------------------------------------------------
# Main PDF render
# -----------------------------------------------------------

def render_pdf(kpi_df: pd.DataFrame, kpi_summary: dict, insights: str,
               recommendations: str, path: str) -> str:
    pdf = ReportPDF()
    pdf.add_page()

    # ---------- Executive Summary ----------
    pdf.section_title("Executive Summary")
    pdf.set_font("DejaVu", "", 11)
    pdf.multi_cell(0, 6, sanitize_text(insights))
    pdf.ln(4)

    # ---------- KPI Summary ----------
    pdf.section_title("Key Performance Indicators")
    pdf.set_font("DejaVu", "B", 11)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(60, 8, "Metric", border=1, align="C", fill=True)
    pdf.cell(60, 8, "Value", border=1, align="C", fill=True)
    pdf.cell(60, 8, "QoQ Δ", border=1, align="C", fill=True)
    pdf.ln()

    pdf.set_font("DejaVu", "", 10)
    for k, v in kpi_summary.items():
        metric = k.replace("_", " ")
        val = str(v)
        change = "–"
        pdf.cell(60, 7, metric, border=1)
        pdf.cell(60, 7, val, border=1)
        pdf.cell(60, 7, change, border=1)
        pdf.ln()

    pdf.ln(4)
    pdf.set_font("DejaVu", "", 10)
    pdf.multi_cell(0, 6, "These KPIs reflect the latest quarter performance with comparative quarter-over-quarter metrics.")

    # ---------- Charts ----------
    pdf.add_page()
    pdf.section_title("Visual KPI Dashboard")
    pdf.set_font("DejaVu", "", 10)
    pdf.multi_cell(0, 6, "The following charts visualize trends in core financial and customer metrics.")
    charts = create_kpi_charts(kpi_df)
    for ch in charts:
        pdf.ln(4)
        pdf.image(ch, w=170)

    # ---------- Recommendations ----------
    pdf.add_page()
    pdf.section_title("Strategic Recommendations")
    pdf.set_font("DejaVu", "", 11)
    pdf.multi_cell(0, 6, sanitize_text(recommendations))
    pdf.ln(8)
    pdf.set_font("DejaVu", "I", 9)
    pdf.set_text_color(90)
    pdf.multi_cell(0, 5, "These recommendations are prioritized based on financial impact, feasibility, and urgency to restore growth trajectory.")
    pdf.set_text_color(0)

    os.makedirs(os.path.dirname(path), exist_ok=True)
    pdf.output(path)
    return path

# -----------------------------------------------------------
# Markdown Summary for Email / Text
# -----------------------------------------------------------

def render_email_md(kpi_summary: dict, insights: str, recommendations: str) -> str:
    text = [
        "Executive Summary",
        sanitize_text(insights.strip()),
        "",
        "Key KPIs (latest & QoQ):",
        *[f"- {k}: {v}" for k, v in kpi_summary.items()],
        "",
        "Strategic Recommendations:",
        sanitize_text(recommendations.strip()),
    ]
    return "\n".join(text)
